[target_info]
problem    = "sk183"
target     = "SK183"
spec_file  = "oe4x01010_x1d.fits"
model_file = "/Users/billyli/Documents/BillyJessExploratory/powr-OB-lmc-vd3.nc"
instrument = "stis_e140m"

[include_wave_range]
wave_range = [ 1250, 1650,]

[exclude_wave_ranges]
dla = [[1180, 1240,] ]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [-75, 350]
drop_species = []

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
