[target_info]
problem    = "pgmw 3058"
target     = "PGMW 3058"
spec_file  = "/Users/billyli/Documents/float-for-morrow/LMC/LMC N11B/PGMW 3058/G160M_1611_LP4_1996.096_16319/lehf1c020_continuumfit_manual.fits"
model_file = "/Users/billyli/Documents/stellar template fitting/powr-OB-lmc-vd3.nc"
instrument = "cos_g160m"

[include_wave_range]
wave_range = [ 1400, 1800,]

[exclude_wave_ranges]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [-75, 350]
drop_species = []

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
