[target_info]
problem = "2dfs_3694"
target = "2DFS-3694"
spec_file = "/Users/billyli/Documents/float-for-morrow/SMC/2DFS-3694/G130M/G130M20/leeyac010_x1dsum.fits"
model_file = "/Users/billyli/Documents/float-for-morrow/continuum/powr-OB-smc.nc"
instrument = "cos_g130m"

[include_wave_range]
wave_range = [ 1295, 1420,]

[exclude_wave_ranges]
gap = [ [ 1270, 1295,],]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [ -75, 350,]
drop_species = [ "FeII", "PII",]

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
