[target_info]
problem = "mcabund_LMC-Sk-70-115"
target = "LMC-Sk-70-115"
spec_file = "/Users/kt/Dropbox/METAL/data/ULLYSES/lmc/hlsp_ullyses_hst_stis_sk-70d115_e140m_dr7_cspec.fits"
model_file = "/Users/kt/Dropbox/METAL/code/carbon_monoxide_systematic/data/stellar-grids/powr-OB-vd3-lmc.nc"
instrument = "stis_e140m"

[include_wave_range]
wave_range = [ 1230, 1600,]

[exclude_wave_ranges]
unfriendly_stellar_line = [ [ 1500, 1505,],]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [ -75, 350,]
drop_species = [ "GaII", "PbII", "XeI",]

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
