[target_info]
problem    = "sbs0335-052-object-1"
target     = "SBS0335-052-OBJECT-1"
spec_file  = "lb7h91010_x1dsum.fits"
model_file = "/Users/billyli/Documents/BillyJessExploratory/powr-OB-lmc-vd3.nc"
instrument = "cos_g130m"

[include_wave_range]
wave_range = [ 1132, 1420,]

[exclude_wave_ranges]
lines = [[1140, 1162,] ]
dla = [[1200, 1220,] ]
gap = [[1270, 1290,] ]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [-25, 25]
drop_species = []

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
