[target_info]
problem    = "cl* ngc 346 els 51"
target     = "CL* NGC 346 ELS 51"
spec_file  = "/Users/billyli/Documents/float-for-morrow/SMC/SMC N66A/Cl* NGC 346 ELS 51/G160M_1623_LP1_648.224_11625/lb2a05040_continuumfit_manual.fits"
model_file = "/Users/billyli/Documents/stellar template fitting/powr-OB-smc-vd3.nc"
instrument = "cos_g160m"

[include_wave_range]
wave_range = [ 1400, 1800,]

[exclude_wave_ranges]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [-75, 350]
drop_species = []

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
