[target_info]
problem    = "cl* ngc 346 els 7"
target     = "CL* NGC 346 ELS 7"
spec_file  = "/Users/billyli/Documents/float-for-morrow/SMC/SMC N66A/Cl* NGC 346 ELS 7/E140M_1425_0.2x0.2_5400.000_7437/o4wr01020_continuumfit_manual.fits"
model_file = "/Users/billyli/Documents/stellar template fitting/powr-OB-smc-vd3.nc"
instrument = "stis_e140m"

[include_wave_range]
wave_range = [ 1250, 1650,]

[exclude_wave_ranges]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [-75, 350]
drop_species = []

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
