[target_info]
problem    = "bat99 114"
target     = "BAT99 114"
spec_file  = "/Users/billyli/Documents/float-for-morrow/LMC/30 Doradus/BAT99 114/G130M_1291_LP5_2072.416_16812/lf2t2c010_continuumfit_manual.fits"
model_file = "/Users/billyli/Documents/stellar template fitting/powr-OB-lmc-vd3.nc"
instrument = "cos_g130m"

[include_wave_range]
wave_range = [ 1135, 1420,]

[exclude_wave_ranges]
dla = [[1180, 1250,] ]
gap = [[1270, 1290,], [1424, 1425,]]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [-75, 350]
drop_species = []

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
