[target_info]
problem    = "pgmw 3120"
target     = "PGMW 3120"
spec_file  = "/Users/billyli/Documents/float-for-morrow/LMC/LMC N11B/PGMW 3120/E140M_1425_0.2x0.06_2291.000_8320/o5ez01010_continuumfit_manual.fits"
model_file = "/Users/billyli/Documents/stellar template fitting/powr-OB-lmc-vd3.nc"
instrument = "stis_e140m"

[include_wave_range]
wave_range = [ 1250, 1650,]

[exclude_wave_ranges]
big_abs = [[1530, 1555,] ]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [-75, 350]
drop_species = []

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
