[target_info]
problem    = "2dfs-3694"
target     = "2DFS-3694"
spec_file  = "leey1c010_x1dsum.fits"
model_file = "/Users/billyli/Documents/BillyJessExploratory/powr-OB-lmc-vd3.nc"
instrument = "cos_g130m"

[include_wave_range]
wave_range = [ 1132, 1420,]

[exclude_wave_ranges]
dla = [[1180, 1240,] ]
gap = [[1270, 1290,] ]

[vshift]
min = 50
max = 550
delta = 50

[vsini]
min = 50
max = 350
delta = 50

[exclude_vranges.ions]
linelist = "ISM"
vrange = [-25, 300]
drop_species = []

[target_info.plot_ranges_kwargs.all_merged]
color = "gainsboro"
